sudo: true
language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler jekyll
before_script:
- chmod +x ./bin/setup
- "./bin/setup"
- bundle exec jekyll build
script:
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension
  --check-opengraph --url-ignore "feed.xml,/facebook.com/"
- "./bin/deploy"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - LC_ALL=en_US.UTF-8
  - JEKYLL_ENV=production
  - secure: AQaIIGTJtChOQ+mHrjS41Hj05PtXwZ0Vjyx0zZ3ZCFQUGk8Ulyp2wq4pT/rIdgJkHdjkfkOKncuhClkjHi33+WWcyoylmIVMCZ98h0DYNufDuKA/SFqiqbmQPBj4hKlj1JDpb5qjIo2yrUNyDfz1h7e3HgVPFcvhcIIgeDmMcdtB0WihlbvvlDY+PN7ZMuPTWcVWXOfESboBvOd1PyHBqFQp/d+dnDGeGMqfzbwyF8y+wHqPdZvBVcPKokpT/m9Us0xyRl9RVp76fH+mIzVS0wRUnBQoQnNZFtGMD/+8fXPmiWa8tsnbcYeDZfZF6k9FQKTr3bagKg13HUbP7UNWgUVVqF896TlLULPSWHjFqXi88WShbz2dBtscttY5RBq/Gwt+/9PPrInCaIw8XWmNwLzZpNv/aqIwRHBW+zt4EH+T+RUui/Tg/CfuWm2I+meXW0IJ3ygexUJaYr+lZdn0DhbYeHUBz0QDILBJd6Yr6BQRsF+DFpymUX+SbPZuEAeOHMqyDkNgVG2atwcGyaaku3In1TQrNDk1hLgFyotWAposlzNlhxFpbCkGVZDYEb8oPjRkj4e85yoAS3NooNnX1Ij+ktzbTdskfBPCQUQdHmsUHZU9n9uYeSCkqxoLg0NrxNcbQdSnYFinchD78DvOUoHUzU9SUKWNBHeRNyKmOOw=
